"""Baseline

Revision ID: 92711e5fd961
Revises: 5d6e217ce6ab
Create Date: 2024-08-20 03:49:29.764966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92711e5fd961'
down_revision: Union[str, None] = '5d6e217ce6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
